spring:
  application:
    name: tikitaka

  # db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true
  
  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # jwt
  jwt:
    secret-key: ${jwt-secret}
    access-token-expiration-in-ms: 3600000
    refresh-token-expiration-in-ms: 86400000